name: Build EvolutionX for rosemary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl wget repo python3 unzip bc bison flex build-essential zip gcc libc6-dev \
        lib32ncurses-dev lib32z1-dev liblz4-tool libncurses5 libssl-dev libxml2 libxml2-utils lzop pngcrush \
        schedtool squashfs-tools xsltproc yasm liblzma-dev liblzo2-dev pngquant aria2 rsync tar \
        libtinfo5 libncurses5 cmake python-is-python3
        sudo apt-get install -y openjdk-17-jdk

    - name: Create working directory
      run: mkdir evolutionx && cd evolutionx

    - name: Initialize repo
      run: |
        cd evolutionx
        repo init -u https://github.com/Evolution-X/manifest -b udc --depth=1

    - name: Clone local manifest (device, vendor, kernel)
      run: |
        mkdir -p evolutionx/.repo/local_manifests
        cat > evolutionx/.repo/local_manifests/roomservice.xml <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="rosemary-devs/android_device_xiaomi_rosemary" path="device/xiaomi/rosemary" remote="github" revision="14.0" />
  <project name="RedmiNote10S/proprietary_vendor_redmi_rosemary" path="vendor/xiaomi/rosemary" remote="github" revision="main" />
  <project name="RedmiNote10S/android_kernel_redmi_rosemary" path="kernel/xiaomi/rosemary" remote="github" revision="main" />
</manifest>
EOF

    - name: Sync source
      run: |
        cd evolutionx
        repo sync -c --force-sync --no-clone-bundle --no-tags -j$(nproc --all)

    - name: Setup environment variables
      run: |
        cd evolutionx
        source build/envsetup.sh
        lunch evolution_rosemary-userdebug

    - name: Start Build
      run: |
        cd evolutionx
        mka bacon -j$(nproc --all)

    - name: Upload ROM to Artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: EvolutionX-ROM
        path: evolutionx/out/target/product/rosemary/*.zip
