name: Build Evolution X for rosemary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          sudo apt-get update

          # Install essential packages
          sudo apt-get install -y \
            git-core \
            gnupg \
            flex \
            bison \
            build-essential \
            zip \
            curl \
            zlib1g-dev \
            gcc-multilib \
            g++-multilib \
            libc6-dev-i386 \
            libncurses-dev \
            x11proto-core-dev \
            libx11-dev \
            lib32z1-dev \
            ccache \
            libgl1-mesa-dev \
            libxml2-utils \
            xsltproc \
            unzip \
            fontconfig \
            python3-venv \
            python3-pip \
            lsb-release \
            git-lfs \
            openjdk-11-jdk \
            openjdk-8-jdk \
            bc \
            libssl-dev \
            liblz4-tool \
            python3-jinja2 \
            libsdl1.2-dev \
            libncurses5-dev \
            cmake \
            ncurses-dev \
            libusb-1.0-0-dev \
            zlib1g-dev \
            libcurl4-openssl-dev \
            libsdl2-dev \
            libxml2 \
            python3-markdown \
            lib32z1-dev \
            lib32ncurses5-dev \
            libgdk-pixbuf2.0-dev \
            libfreetype6-dev \
            libjpeg-dev \
            libpng-dev \
            libopenjdk-11-jdk \
            libboost-all-dev \
            libatlas-base-dev \
            libssl-dev \
            libffi-dev \
            libgl1-mesa-dev \
            clang \
            llvm \
            binutils \
            bzip2 \
            libtiff-dev \
            libgif-dev \
            libvpx-dev

          # Attempt to install the missing ncurses package and fall back to alternative versions if not found
          sudo apt-get install -y lib32ncurses6-dev || sudo apt-get install -y lib32ncurses5-dev || sudo apt-get install -y lib32ncurses-dev || echo "Failed to install ncurses packages"

          # Ensure the git-lfs is initialized
          git lfs install

      - name: Install repo tool
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > repo
          chmod +x repo
          sudo mv repo /usr/local/bin/

      - name: Initialize repo
        run: |
          mkdir evolutionx
          cd evolutionx
          repo init -u https://github.com/Evolution-X/manifest -b vic --git-lfs
          mkdir -p .repo/local_manifests
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <manifest>
            <project name="Evolution-X-Devices/device_xiaomi_rosemary" path="device/xiaomi/rosemary" remote="github" revision="main"/>
            <project name="RedmiNote10S/android_vendor_xiaomi_rosemary" path="vendor/xiaomi/rosemary" remote="github" revision="main"/>
            <project name="RedmiNote10S/android_kernel_redmi_rosemary" path="kernel/xiaomi/rosemary" remote="github" revision="main"/>
          </manifest>' > .repo/local_manifests/roomservice.xml

      - name: Sync source
        run: |
          cd evolutionx
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags || true
          # Retry sync if initial sync fails
          if [ $? -ne 0 ]; then
            echo "Repo sync failed, retrying..."
            repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
          fi

      - name: Build ROM
        run: |
          cd evolutionx
          source build/envsetup.sh
          lunch evolution_rosemary-userdebug
          m evolution

      - name: Archive build
        run: |
          cd evolutionx
          mkdir -p /artifacts
          cp out/target/product/rosemary/*.zip /artifacts/
        continue-on-error: true
