name: Evolution X Build (Android 14)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Java 17
        run: |
          sudo apt update
          sudo apt install openjdk-17-jdk -y
          java -version

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git \
            repo \
            curl \
            wget \
            zip \
            unzip \
            bc \
            bison \
            build-essential \
            ccache \
            clang \
            flex \
            g++-multilib \
            gcc-multilib \
            gnupg \
            gperf \
            libncurses-dev \
            libssl-dev \
            lzop \
            pngcrush \
            schedtool \
            squashfs-tools \
            xsltproc \
            zlib1g-dev \
            libxml2-utils \
            liblz4-tool \
            libtinfo-dev \
            lib32z1-dev \
            libtinfo6 \
            lib32ncurses5-dev \
            libncurses5-dev \
            lib32ncurses6-dev \
            libncurses6-dev \
            ncurses-base \
            ncurses-term \
            openjdk-11-jdk \
            lib32stdc++6 \
            lib32gcc1 \
            lib32ncurses5 \
            libxml2 \
            libtool \
            bzr \
            rsync \
            libssl-dev \
            automake \
            autoconf \
            libncurses5

      - name: Initialize repo
        run: |
          mkdir -p ~/.repo
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.repo/repo
          chmod a+x ~/.repo/repo

      - name: Repo sync (Evolution X)
        run: |
          mkdir evolutionx
          cd evolutionx
          repo init -u https://github.com/Evolution-X/android.git -b thirteen --depth=1
          git clone https://github.com/Evolution-X-Devices/device_xiaomi_rosemary -b udc device/xiaomi/rosemary
          git clone https://github.com/TheMuppets/proprietary_vendor_xiaomi -b udc vendor/xiaomi/rosemary
          git clone https://github.com/xdt-devs/kernel_xiaomi_mt6785 -b udc kernel/xiaomi/rosemary
          repo sync -j4

      - name: Set up build environment
        run: |
          cd evolutionx
          source build/envsetup.sh
          lunch evolution_rosemary-userdebug

      - name: Start building
        run: |
          cd evolutionx
          mka bacon
